# Generated by Django 3.2.9 on 2021-12-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='guide_confirmation',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
