# Generated by Django 3.2.9 on 2021-12-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_guide_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
