# Generated by Django 3.2.9 on 2021-12-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='profile_pic',
        ),
    ]
