# Generated by Django 3.2.9 on 2021-12-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_author_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replies',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
