# Generated by Django 3.2.9 on 2021-12-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_category_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='profile_image',
            new_name='category_image',
        ),
    ]
