# Generated by Django 3.2.9 on 2021-12-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_post_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, to='forum.Category'),
        ),
    ]
