# Generated by Django 3.2.9 on 2021-12-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_rename_profile_image_category_category_image'),
        ('forum', '0009_post_closed'),
    ]

    operations = [
    ]
