# Generated by Django 3.2.9 on 2021-12-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_merge_20211218_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='points',
        ),
    ]
