# Generated by Django 3.2.9 on 2021-12-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_remove_author_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fullname',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
