# Generated by Django 3.2.9 on 2021-12-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20211204_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vote_ration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vote_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
