# Generated by Django 3.2.9 on 2021-12-18 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20211218_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-vote_ration', '-vote_total', 'title']},
        ),
    ]
